config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'accounts#index'
  get 'profile/:username', to: 'accounts#profile', as: :profile
  root to: "public#home"
  #likes in production make it post method not get method cuz it might leat too caohs
  get 'post/like/:post_id', to: 'likes#save_like', as: :likepost

    post "follow/account", to: "accounts#follow_account",as: :follow_account
  resources :posts, only: [:new,:create,:show]
  resources :comments, only: [:create]


end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
         has_many :posts
         has_many :likes
         
         def full_name
          "#{first_name} #{last_name}"
         end
         def total_followers
           Follower.where(follower_id: self.id).count
         end
         def total_following
           Follower.where(following_id: self.id).count
         end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account

attr_accessor :return_to

after_create :increase_post_comment_counter
after_destroy :decreaes_post_comment_counter

private
def increase_post_comment_counter
  Post.find(self.post_id).increment(:total_comment_count).save
end
def decreaes_post_comment_counter
  Post.find(self.post_id).decrement(:total_comment_count).save
end
end

app/models/follower.rb
class Follower < ApplicationRecord
  #belongs_to :accounts
  validates_uniqueness_of :follower_id, scope: :following_id


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :account
  validates_uniqueness_of :post_id, scope: :account_id

  after_create :increase_post_like_counter
  after_destroy :decreaes_post_like_counter

  private
  def increase_post_like_counter
    Post.find(self.post_id).increment(:total_likes_count).save
  end
  def decreaes_post_like_counter
    Post.find(self.post_id).decrement(:total_likes_count).save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope {order(created_at: :desc)}
  mount_uploader :image, ImageUploader
  belongs_to :account
  has_many :likes
    has_many :comments
  before_save :set_active
  scope :active, -> { where active: true }

  def total_likes
    0
  end
  private
  def set_active
    self.active = true
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  #devvise model name account
  before_action :authenticate_account!
  before_action :set_account, only: [:profile]
  def index
    #user dashboard
    followers_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    followers_ids << current_account.id

    @posts = Post.includes(:account).where(account_id: followers_ids).active
    @comment = Comment.new
    following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    following_ids << current_account.id
    @followers_suggestions= Account.where.not(id: following_ids)

  end

  def profile
   @posts = @account.posts.active
  end
  def follow_account
   follower_id = params[:follow_id]
   Follower.create(follower_id: current_account.id, following_id: follower_id)

   redirect_to dashboard_path
  end
  private
  def set_account
    @account = Account.find_by_username(params[:username])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :image,:image_cache, :description, :website])
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :image,:image_cache, :description, :website])
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_account!

  def create
    @comment = Comment.new(comment_params)
    @comment.account_id = current_account.id if account_signed_in?

    if @comment.save
      return_url = params[:comment][:return_to].present? ? post_path(@comment.post_id) : dashboard_path
      redirect_to dashboard_path, flash: {success:"your comment has been uploaded"}
    else
      redirect_to dashboard_path, flash: {danger:"your comment has been uploaded"}
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id, :return_to)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_account!

  def save_like
    @like = Like.new(post_id: params[:post_id], account_id: current_account.id)
    @post_id = params[:post_id]
    existing_like = Like.where(post_id: params[:post_id], account_id: current_account.id)

      respond_to do |format|
        format.js{
          #this to check if he likes a post then dislike it if not then like it
          if existing_like.any?
             existing_like.first.destroy
             @success = false
          elsif @like.save
              @success = true
            else
              @success = false
            end
            #render js file from the views
              render "posts/like"
              @post_likes = Post.find(@post_id).total_likes_count
      }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!
    before_action :set_post, only: [:show]

  def new
   @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id if account_signed_in?
    if @post.save
      redirect_to dashboard_path, flash: {success:"your image has been uploaded"}
    else
      redirect_to new_post_path, flash: {danger:"your image has been uploaded"}
    end

  end

  def show
   @comment = Comment.new
   @comments = Comment.includes(:account).where(post_id: @post.id)
  end

  private
  def set_post
  @post = Post.find(params[:id]) if params[:id].present?
  end
  def post_params
    params.require(:post).permit(:image, :image_cache, :description)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home

  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def profile_picture account
    image_path = account.image.url.present? ? account.image.url : "default.jpeg"
    image_tag(image_path, width:"40px",class:"img-circle")
  end

  def can_edit_profile? profile_id
    account_signed_in? && current_account.id = profile_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_like_by_user? post_id
    Like.where(post_id: post_id, account_id: current_account.id).any?
  end
end

app/views/accounts/_followers_suggestions.html.erb
<% @followers_suggestions.each do |account| %>
<div class="recommended-follower">
  <div class="row">
    <div class="col-sm-3 col-lg-2">
      <%= link_to profile_picture(account),profile_path(account.username) %>
    </div>
    <div class="col-sm-9 col-lg-10">
      <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
      <%= hidden_field_tag :follow_id, account.id %>
      <%= submit_tag "Follow", class: "btn btn-info", class: "btn btn-info btn-sm" %>
      <% end %>
      <%= link_to account.full_name, profile_path(account.username), class:"text-dark" %>
      <p class="text-muted" style="font-size: 12px;">
        <%= account.created_at > 1.day.ago ? "New to instagram" : "Followed by X users" %>
      </p>
    </div>
  </div>
</div>
<% end %>

app/views/accounts/index.html.erb
<% @posts.each do |post| %>
  <div class="container">
    <div class="row">
      <div class="col-8 mt-10" style="margin-top: 1rem;">
        <div class='card-header'>
          <%= image_tag post.account.image.url, width:"40px",class:"img-circle" %>

          <%= link_to post.account.full_name, profile_path(post.account.username), class:"text-dark" %>
        </div>
        <%= image_tag post.image.url, class: "img img-fluid" %>

        <div class="post-details">
          <div class="post-action">
            <i class="fa fa-heart fa-2x like-<%= post.id %> <%= 'active' if post_like_by_user?(post.id ) %> post-like" data-id="<%= post.id %>"></i>
          <%= link_to post_path(post.id) do %>
            <i class="fa fa-comment fa-2x post-comment"></i>
          <% end %>

          </div>
          <p>
            <strong id="post-<%= post.id %>-likes"><%= post.total_likes_count %> Likes</strong>
          </p>
          <p>
            <strong id="post-<%= post.id %>-comment"><%= link_to post.account.username,profile_path(post.account.username),class:"text-dark" %></strong>
          </p>
          <%= simple_format post.description %>
          <p class="text-muted"><%= time_ago_in_words post.created_at %>
            ago</p>
            <%= render 'posts/comments',post: post%>
        </div>
        <div class="comment-box">
          <%= form_for @comment do |f| %>
          <%= f.hidden_field :post_id, value: post.id %>
          <div class="input-group " style="">
            <%= f.text_field :comment, placeholder: "Add comment here......", class: "form-control" %>
          <div class="input-group-append">
            <%= f.submit "Post", class: "btn btn-success float-right" %>
          </div>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="col-4">
      <div class="user-summary">
        <%= link_to image_tag(current_account.image.url, width:"40px",class:"img-circle"),profile_path(current_account.username) %>
        <strong><%= current_account.username %></strong><br>
        <%= current_account.full_name %>
      </div>
      <div class="followers">

        <%= link_to "View all","#",class: "float-right text-draked"%>

        <p class="text-muted">Suggestions for you</p>
        <%= render "accounts/followers_suggestions" %>
      </div>
    </div>
  </div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8" style="display: contents;margin-right:3rem">
      <%= image_tag @account.image.url,width:"200px", class: "img-circle" %>
    </div>
    <div class="col-5" style="background: #fafafa;border: 1px solid #fafafa;">
      <%= link_to "edit", edit_account_registration_path,class:"btn btn-scondary float-right" if can_edit_profile?(@account.id) %>
      <h1><%= @account.full_name %></h1>
      <div class="profile-status"><%= @account.posts.count %>
        posts</div>
      <div class="profile-status"><%= @account.total_followers %>
        followers</div>
      <div class="profile-status"><%= @account.total_following %>
        following</div>

      <p><%= @account.full_name %></p>
      <p><%= @account.description %></p>
      <p><%= link_to @account.website if @account.website.present? %></p>
    </div>
  </div>
  <div class="row">
    <% @posts.each do |post| %>
    <div class="col-4" style="margin-top:4%;">
      <div class="insta-post post-square" style="background: url(<%= post.image.url %>) no-repeat center top">
        <%= link_to post_path(post) do %>
      <div class="post-stats">
        <div class="inner">
          <i class=" fa fa-heart "></i> <%= post.total_likes_count %>
          <i class="fa fa-comment m-l-15"></i> <%= post.total_comment_count %>
        </div>
      </div>
      <% end%>
    </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-white bg-white">
    <div class="container">
      <div class="navbar-brand">
         <i class="fa fa-instagram"></i> | <%= link_to 'LikeInsta',account_signed_in? ? dashboard_path : root_path, class: "navbar-brand" %>
      </div>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
            <ul class="navbar-nav ml-auto">
              <% if account_signed_in? %>
              <%= link_to 'Home',dashboard_path, class: "nav-link" %>
              <%= link_to 'New Post',new_post_path, class: "nav-link" %>
              <%= link_to 'My Profile', profile_path(current_account.username), class: "nav-link" %>
              <%= link_to 'Sign out',destroy_account_session_path, method: :delete, class: "btn folat-right" %>
              <% else %>
              <%= link_to "Sign-in",  new_account_session_path,class: "btn btn-outline-success folat-right" %>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instgram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>


          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
  </body>
</html>

app/views/posts/_comments.html.erb
<% post.comments.each do |comment| %>
<div class="comment">
    <%= image_tag comment.account.image.url,width:"200px", class: "img-circle comment-img" %>
<strong><%= link_to comment.account.username,profile_path(comment.account.username) %></strong>
  <%= comment.comment %>
  <p class="text-muted"><%= time_ago_in_words comment.created_at %></p>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post , html: {multiple: true} do |f| %>
<div class="form-group">
<%= f.file_field :image %>
<%= f.hidden_field :image_cache %>
</div>
<div class="form-group">
<%= f.label :description %>
<%= f.text_area :description,class:"form-control" %>
</div>
<%= f.submit "Upload",class:"btn btn-success"  %>

<% end %>

app/views/posts/like.js.erb
<% if @success == true %>
$(".like-<%= @post_id %>").addClass("active");
<% else %>
$(".like-<%= @post_id %>").removeClass("active");
<% end %>
$("#post-<%= @post_id %>").text("<%= @post_likes %>  likes");

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>new post</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-8 mt-10" style="   padding: 0px;">
        <%= image_tag @post.image.url, class: "img img-fluid" %>
      </div>

    <div class="col-4 right-side">
    <p>
        <%= image_tag @post.account.image.url, width:"40px",class:"img-circle" %>

          <strong id="post-<%= @post.id %>-comment"><%= link_to @post.account.username,profile_path(@post.account.username),class:"text-dark " %></strong>
        </p>

      <div class="post-details">
        <div class="comments-feed">
        <%= simple_format @post.description %>
        <%= render 'posts/comments',post: @post%>
        </div>

        <div class="post-action">
          <i class="fa fa-heart fa-2x like-<%= @post.id %> <%= 'active' if post_like_by_user?(@post.id ) %> post-like" data-id="<%= @post.id %>"></i>
          <i class="fa fa-comment fa-2x post-comment" id="post-comment"></i>
        </div>
        <p>
          <strong id="post-<%= @post.id %>-likes"><%= @post.total_likes_count %>
            Likes</strong>
        </p>

        <p class="text-muted" style="font-size: 13px;color: #a9a9a9 !important;"><%= time_ago_in_words @post.created_at %>
          ago</p>

      </div>

      <div class="comment-box">
        <%= form_for @comment do |f| %>
        <%= f.hidden_field :post_id, value: @post.id %>
          <%= f.hidden_field :return_to, value: @post.id %>
        <div class="input-group " style="">
          <%= f.text_field :comment, placeholder: "Add comment here......", class: "form-control" %>
          <div class="input-group-append">
            <%= f.submit "Post", class: "btn btn-success float-right" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>